# Site settings
title: jcaseydev.com
email: jcaseydev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Justin Casey - Software Engineer
baseurl: # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  jmcs811

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


